name: Bug report
description: Report a reproducible defect
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
      placeholder: Steps, expected behavior, actual behavior
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Please provide minimal reproducible steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Environment
      description: OS, Python version, run mode
      placeholder: macOS 14, Python 3.11, FastAPI sync
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant traceback or screenshots
